/* SCE CONFIDENTIAL
PlayStation(R)3 Programmer Tool Runtime Library 310.001
* Copyright (C) 2006 Sony Computer Entertainment Inc.
* All Rights Reserved.
*/
#ifndef __DTLIB_DEFINES_H__
#define __DTLIB_DEFINES_H__

#define DTLIB_OK 0
#define DTLIB_ERROR_BASE  50000

#define DTLIB_INVALID_TARGETNAME    (DTLIB_ERROR_BASE+1)
#define DTLIB_INVALID_SOCKET        (DTLIB_ERROR_BASE+2)
#define DTLIB_INVALID_PCK           (DTLIB_ERROR_BASE+3)
#define DTLIB_INVALID_PERM          (DTLIB_ERROR_BASE+4)
#define DTLIB_ERROR_READ            (DTLIB_ERROR_BASE+5)
#define DTLIB_INVALID_SIZE          (DTLIB_ERROR_BASE+6)

#define DTLIB_DCMP_BASE             (DTLIB_ERROR_BASE+100)
#define DTLIB_DCMP_INVALHEAD	    (DTLIB_DCMP_BASE)
#define DTLIB_DCMP_SYSTEM_OFF	    (DTLIB_DCMP_BASE+1)
#define DTLIB_DCMP_SYSTEM_SUSPENDED (DTLIB_DCMP_BASE+2)
#define DTLIB_DCMP_LPAR_NONE        (DTLIB_DCMP_BASE+3)
#define DTLIB_DCMP_LPAR_SUSPENDED   (DTLIB_DCMP_BASE+4)
#define DTLIB_DCMP_NOCONNECT	    (DTLIB_DCMP_BASE+5)
#define DTLIB_DCMP_NOPROTO	        (DTLIB_DCMP_BASE+6)
#define DTLIB_DCMP_PRIORITY         (DTLIB_DCMP_BASE+7)
#define DTLIB_DCMP_NOSPACE	        (DTLIB_DCMP_BASE+8)
#define DTLIB_DCMP_VERSION          (DTLIB_DCMP_BASE+10)

#define DTLIB_NETMP_BASE            (DTLIB_ERROR_BASE+120)
#define DTLIB_NETMP_INVAL           (DTLIB_ERROR_BASE+121)
#define DTLIB_NETMP_BUSY            (DTLIB_ERROR_BASE+122)
#define DTLIB_NETMP_NOTCONNECT      (DTLIB_ERROR_BASE+123)
#define DTLIB_NETMP_ALREADYCONN     (DTLIB_ERROR_BASE+124)
#define DTLIB_NETMP_NOMEM           (DTLIB_ERROR_BASE+125)
#define DTLIB_NETMP_INVALLPAR       (DTLIB_ERROR_BASE+126)
#define DTLIB_NETMP_INVALPRIORITY   (DTLIB_ERROR_BASE+127)
#define DTLIB_NETMP_INVALPROTO      (DTLIB_ERROR_BASE+128)
#define DTLIB_NETMP_POWER_OFF       (DTLIB_ERROR_BASE+129)
#define DTLIB_NETMP_NODECI_CONNECT  (DTLIB_ERROR_BASE+130)
#define DTLIB_NETMP_NOREGISTER      (DTLIB_ERROR_BASE+131)
#define DTLIB_NETMP_ALREADY_REGISTER    (DTLIB_ERROR_BASE+132)

#define DTLIB_SOCKET_CLOSE          (DTLIB_ERROR_BASE+141)
#define DTLIB_WAIT_TIMEOUT          (DTLIB_ERROR_BASE+142)
#define DTLIB_DONT_CONTINUE         (DTLIB_ERROR_BASE+143)


#define DTLIB_NG                    (DTLIB_ERROR_BASE+200)
#define DTLIB_TOO_BIG_PACKET        (DTLIB_ERROR_BASE+201)



#endif //__DTLIB_DEFINES_H__
