%(/*)
#########################################################
# SCE CONFIDENTIAL
# PlayStation(R)3 Programmer Tool Runtime Library 310.001
# Copyright (C) 2009 Sony Computer Entertainment Inc.
# All Rights Reserved.
#########################################################
%(*/)\
$(copyrightSourceHeader)

///////////////////////////////////////////////////////////////////////////////
//
//  JDL GENERATED FILE - DO NOT EDIT THIS FILE DIRECTLY
// 
///////////////////////////////////////////////////////////////////////////////
#ifndef %(MAKE_SYMBOL)$(_FILENAME_)%(END)
#define %(MAKE_SYMBOL)$(_FILENAME_)%(END)

#include <cell/swcache/patch_vtable.h>

%(IF_EXIST:namespace)%(FOR_TOKENS:namespace:$(COLON)$(SPACE))namespace $(TOKEN) { %(END)$(NEWLINE)%(END)\
class  ClassIdTabFor_$(class) :public cell::swcache::ClassIdTabHeader {
public:
	enum ClassId
	{
		id_start = 0,
%(FOR_TOKENS:VirtualClassList)\
%( IF_NOT_EXIST:$(TOKEN)_mangle)\
%(  ERROR) mangled symbol for class $(TOKEN) is not specified%(END)\
%( END)\
		id_%(MAKE_SYMBOL)$(TOKEN)%(END),
%(END)\
		NumOfIds
	};

	ClassIdTabFor_$(class)(){}
	void init() {
		static bool s_initialized = false;
		if (s_initialized) return;
%(FOR_TOKENS:VirtualClassList)\
		extern char _ZTV$($(TOKEN)_mangle)[];
		insertVtab(_ZTV$($(TOKEN)_mangle), id_%(MAKE_SYMBOL)$(TOKEN)%(END));
%(END)\
		s_initialized = true;
	}

private:
	ClassIdTabHeader::Vtab2id tab[NumOfIds-1];
};
%(IF_EXIST:namespace)%(FOR_TOKENS:namespace:$(COLON)$(SPACE))} %(END)%(END)\

#endif // %(MAKE_SYMBOL)$(_FILENAME_)%(END)
 
