#########################################################
# SCE CONFIDENTIAL
# Copyright (C) 2009 Sony Computer Entertainment Inc.
# All Rights Reserved.
#########################################################

#########################################################
##
##  JDL GENERATED FILE - DO NOT EDIT THIS FILE BY HAND
## 
#########################################################

CELL_MK_DIR ?= $($)(CELL_SDK)/samples/mk
include $($)(CELL_MK_DIR)/sdk.makedef.mk
include $($)(CELL_SDK)/samples/sdk/prx/mk/prx.mk

%(FOR_METHODS)\
SPURS_JOBS += $(spuBinaryPrefix)$(managedFilePrefix)$(JobFileName_macro)$(jobFilePostfix).bin
%(END)\

PPU_INCDIRS += -I$(build2JdlPath)$(jdl2HeaderPath)
PPU_PRX_LDFLAGS += -llv2_stub
PPU_SRCS = $(build2JdlPath)$(jdl2PpuCppPath)$(managedFilePrefix)$(class)_prx.cpp $($)(SPURS_JOBS)

PPU_PRX_TARGET 	= $(build2TargetPath)$(class).prx

CLEANFILES += $(managedFilePrefix)$(class)_prx.ppu.o $(managedFilePrefix)$(class)_prx.ppu.d

stub:

include $($)(CELL_MK_DIR)/sdk.target.mk
include $($)(CELL_SDK)/samples/sdk/prx/mk/prx_target.mk

# Local Variables:
# mode: Makefile
# End:

